# Generated by Django 5.0.6 on 2024-06-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='coment',
            field=models.TextField(verbose_name='Comentario'),
        ),
    ]
